export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const LIKE_COMMENT = "LIKE_COMMENT";
export const EDIT_COMMENT = "EDIT_COMMENT";
export const ADD_REPLY_COMMENT = "ADD_REPLY_COMMENT";
export const LIKE_REPLY_COMMENT = "LIKE_REPLY_COMMENT";
export const DELETE_REPLY_COMMENT = "DELETE_REPLY_COMMENT";
export const EDIT_REPLY_COMMENT = "EDIT_REPLY_COMMENT";

export const HOLD_EDIT_COMMENT = "HOLD_EDIT_COMMENT";
